---
- name: Change the instance type
  vars:
    regions_list: "{{ regions_list }}"
    software: "{{ software }}"
    change_instance_to: "{{ change_instance_to }}"
  hosts: production
  serial: 1
  tasks:
    - name: Gather packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Print if package found
      ansible.builtin.debug:
        msg: " '{{ software }}' found"
      when: "'{{ software }}' in ansible_facts.packages"
    
    - name: Get instance ID
      amazon.aws.ec2_metadata_facts:
   
    - name: Display Instance ID
      debug:
        var: ansible_ec2_instance_id

    - name: Stop instance
      delegate_to: localhost
      amazon.aws.ec2_instance:
        region: "{{ regions_list }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
        state: stopped
        wait: true
      when: "'{{ software }}' in ansible_facts.packages"

    - name: Change instance type
      delegate_to: localhost
      shell: >
        aws ec2 modify-instance-attribute --instance-id {{ ansible_ec2_instance_id
        }}  --instance-type {{ change_instance_to}} --region {{ regions_list }}
      when: "'{{ software }}' in ansible_facts.packages"
      
    - name: Start instance
      delegate_to: localhost
      amazon.aws.ec2_instance:
        region: "{{ regions_list }}"
        instance_ids: "{{ ansible_ec2_instance_id }}"
        state: running
      when: "'{{ software }}' in ansible_facts.packages"

- name: Install Softwares in web server
  hosts: web
  become: true
  tasks:
  - name: Install apache2
    apt: 
      name: apache2
      state: latest

- name: Install software in DB server
  hosts: db 
  become: true
  tasks:
  - name: install mysql
    apt:
      name: mysql-server
      state: latest
